name: New Bug Report
description: File a bug report
title: "Short description of bug"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this issue! We will look into it and respond as soon as possible.

        Please try to give your issue a good title.

  - type: markdown
    attributes:
      value: |
        #

  - type: Summary
    attributes:
      label: What happened?
      description: "**Hot Tip:** A clear and concise description of the bug (e.g., 'Dashboard crashes when selecting XYZ option'). Record your screen and attach it here."
    validations:
      required: true

  - type: textarea
    attributes:
      label: How do we reproduce it?
      description: "Provide detailed steps to replicate the issue. **Hot Tip:** Attach a screen recording, screenshot, or log file (use ``` for logs) to illustrate the issue."
      placeholder: "Steps to reproduce..."
      value: |
        1. [e.g., Go to the Dashboards page]
        2. [e.g., Click the XYZ button]
        3. [e.g., Select option ABC]
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected Result
      description: "Describe what you expected to happen (e.g., The dashboard should load without errors)."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Actual Result
      description: "Describe what actually happened."
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: "Details about your setup."
      value: |
      - **Plugin Version:** [e.g., 2.5.0]
      - **Grafana Version:** [e.g., 11.0.0]
      - **Datasource(s):** [e.g., Prometheus, MySQL]
      - **Operating System:** [e.g., Ubuntu 20.04] (optional)
      - **Browser:** [e.g., Chrome 120] (optional)
    validations:
      required: true

  - type: checkboxes
    attributes:
      label: "Did this work before?"
      options:
        - label: "Yes"
          required: false
        - label: "No"
          required: false

  - type: textarea
    attributes:
      label: Details if this work before.
      description: "Specify the grafana and plugin versions where it worked"
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context (Optional).
      description: "Any extra details that might help, such as: Recent changes (e.g., upgrades, config edits), Frequency of the issue (e.g., always, intermittent)."
    validations:
      required: false
