name: Suggest a Feature
description: Suggest an idea for this project
title: "Short description of feature"
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting this issue! We will look into it and respond as soon as possible.

        Please try to give your issue a good title.

  - type: markdown
    attributes:
      value: |
        #

  - type: textarea
    attributes:
      label: Why Is This Needed?
      description: "Describe the problem this feature would solve or the use case it addresses."
      placeholder: |
        - What challenge are you facing without this feature?
        - How would it improve your experience?
    validations:
      required: true

  - type: textarea
    attributes:
      label: What Would You Like to Be Added?
      description: "Provide a clear and concise description of the feature or enhancement."
      placeholder: |
        - What should it do?
        - Include any specific functionality or behavior you envision (e.g., new UI element, API support).
    validations:
      required: true

  - type: textarea
    attributes:
      label: Who Is This Feature For?
      description: "Explain the target audience for this feature.."
      placeholder: |
        - What type of user would benefit (e.g., developers, admins, end-users)?
        - How broadly do you think it would be used?
    validations:
      required: false

  - type: textarea
    attributes:
      label: Additional Context (Optional)
      description: "Add any extra details, such as:"
      placeholder: |
        - Examples from other tools/projects with similar features.
        - Mockups, sketches, or screenshots (if applicable).
        - Relevant workflows or scenarios.
    validations:
      required: false
